language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install --upgrade pip
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install --upgrade python
  - python --version
  - pip --version
  - pip install -r requirements.txt
# command to run tests
script: python setup.py test
os:
  - linux
  
  